'use client';
import {useEffect,useRef,useState} from 'react';
import type {Map as LeafletMap,LayerGroup} from 'leaflet';
import type {Listing} from '@/lib/listings';
export default function CityMap({items,selected,onSelect}:{items:Listing[];selected:string|null;onSelect:(id:string)=>void}){
 const el=useRef<HTMLDivElement>(null), map=useRef<LeafletMap|null>(null), group=useRef<LayerGroup|null>(null), lastItems=useRef<Listing[]|null>(null); const [ready,setReady]=useState(false),[failed,setFailed]=useState(false); const callback=useRef(onSelect);callback.current=onSelect;
 useEffect(()=>{let disposed=false;let timer:ReturnType<typeof setTimeout>;import('leaflet').then(L=>{if(disposed||!el.current)return;const m=L.map(el.current,{zoomControl:false,scrollWheelZoom:true,wheelDebounceTime:60,wheelPxPerZoomLevel:100}).setView([12.953,77.614],12);map.current=m;L.control.zoom({position:'bottomright'}).addTo(m);const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(m);tiles.on('tileerror',()=>setFailed(true));tiles.on('load',()=>clearTimeout(timer));timer=setTimeout(()=>setFailed(true),10000);group.current=L.layerGroup().addTo(m);setReady(true);const observer=new ResizeObserver(()=>m.invalidateSize());observer.observe(el.current);m.on('unload',()=>observer.disconnect());}).catch(()=>setFailed(true));return()=>{disposed=true;clearTimeout(timer);map.current?.remove();map.current=null;};},[]);
 useEffect(()=>{if(!ready||!map.current||!group.current)return;import('leaflet').then(L=>{group.current?.clearLayers();items.forEach((p)=>{if(!p.coords)return;const active=p.id===selected;const symbol:Record<string,string>={cafes:'☕',food:'◆',malls:'▦',cinema:'▤',sports:'⚽',gigs:'♫'};const marker=L.marker(p.coords,{icon:L.divIcon({className:'custom-marker',html:`<span class="pin ${p.category} ${active?'active':''}"><b class="pin-symbol">${symbol[p.category]}</b></span>`,iconSize:[46,46],iconAnchor:[23,46]}),title:p.title,alt:`Select ${p.title}`,zIndexOffset:active?1000:0});marker.on('click',()=>callback.current(p.id));marker.addTo(group.current!);marker.getElement()?.setAttribute('aria-label',`Select ${p.title}`);});if(lastItems.current!==items){lastItems.current=items;const points=items.flatMap(p=>p.coords?[p.coords]:[]);if(points.length>1)map.current?.fitBounds(L.latLngBounds(points),{paddingTopLeft:[40,42],paddingBottomRight:[40,matchMedia('(max-width: 760px)').matches?225:165],maxZoom:12,animate:false});else if(points.length===1)map.current?.setView(points[0],13,{animate:false});}const chosen=items.find(p=>p.id===selected);if(chosen?.coords)map.current?.panTo(chosen.coords,{animate:!matchMedia('(prefers-reduced-motion: reduce)').matches});});},[items,selected,ready]);
 return <><div ref={el} className="map-canvas" aria-label="Map of approximate Bengaluru listing locations"/>{!ready&&!failed&&<div className="map-status" role="status">Finding our way around Bengaluru…</div>}{failed&&<div className="map-fallback"><strong>Map tiles are unavailable</strong><p>You can still explore every neighbourhood below.</p><div>{items.map(p=><button key={p.id} onClick={()=>onSelect(p.id)} aria-pressed={p.id===selected}>{p.neighbourhood} · {p.title}</button>)}</div><button onClick={()=>location.reload()}>Reload map</button></div>}</>;
}

