'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import dynamic from 'next/dynamic';
import {ArrowUpRight,Bookmark,Search,MapPin,ArrowRight,Sun,Moon,Coffee,Clapperboard,Volleyball,X,Clock,Map as MapIcon,List,Check,Utensils,ShoppingBag,Music2,Navigation,Menu} from 'lucide-react';
import {categories,dateOffset,demoProvider,localISODate,type Listing,type Category} from '@/lib/listings';
const CityMap=dynamic(()=>import('@/components/CityMap'),{ssr:false,loading:()=> <div className="map-status">Loading the city map…</div>});
const icons={cafes:Coffee,food:Utensils,malls:ShoppingBag,cinema:Clapperboard,sports:Volleyball,gigs:Music2};
const placeCategories:Category[]=['cafes','food','malls'];
const eventCategories:Category[]=['cinema','sports','gigs'];
const dateLabel=(date:string)=>new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',timeZone:'UTC'}).format(new Date(`${date}T12:00:00Z`));
const kmBetween=(a:[number,number],b:[number,number])=>{const r=Math.PI/180,dLat=(b[0]-a[0])*r,dLon=(b[1]-a[1])*r,x=Math.sin(dLat/2)**2+Math.cos(a[0]*r)*Math.cos(b[0]*r)*Math.sin(dLon/2)**2;return 12742*Math.asin(Math.sqrt(x));};
export default function Home(){
 const [mode,setMode]=useState<'all'|'tonight'|'explore'>('all'),[category,setCategory]=useState<Category|'all'>('all'),[area,setArea]=useState('all'),[day,setDay]=useState('all'),[query,setQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[savedOnly,setSavedOnly]=useState(false),[saved,setSaved]=useState<string[]>([]),[items,setItems]=useState<Listing[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[storageError,setStorageError]=useState(''),[selected,setSelected]=useState<string|null>(null),[detail,setDetail]=useState<Listing|null>(null),[info,setInfo]=useState<'about'|'sources'|null>(null),[menuOpen,setMenuOpen]=useState(false),[mobileMap,setMobileMap]=useState(false),[toast,setToast]=useState('');
 const dialog=useRef<HTMLDialogElement>(null),infoDialog=useRef<HTMLDialogElement>(null),searchRef=useRef<HTMLInputElement>(null);
 const [nearby,setNearby]=useState<Listing|null>(null);
 const [locationError,setLocationError]=useState('');
 const useMyLocation=()=>{if(!navigator.geolocation){setLocationError('Location is unavailable in this browser. Choose a neighbourhood or place instead.');return;}navigator.geolocation.getCurrentPosition(position=>{if(kmBetween([12.9716,77.5946],[position.coords.latitude,position.coords.longitude])>65){setLocationError('Your current location is outside the Bengaluru preview area. Choose a neighbourhood instead.');return;}const center:Listing={id:'my-location',title:'Your location',category:'malls',neighbourhood:'your area',address:'Your current location',description:'Nearby preview picks',tag:'Nearby',source:'#',sourceLabel:'Your location',coords:[position.coords.latitude,position.coords.longitude]};setLocationError('');showNearby(center);},()=>setLocationError('Location access was unavailable. Choose a neighbourhood or place instead.'),{enableHighAccuracy:false,timeout:8000});};
 const today=localISODate(),lastDate=dateOffset(2);
 const load=()=>{setLoading(true);setError('');demoProvider.getListings().then(setItems).catch(()=>setError('The city guide couldn’t load. Please try again.')).finally(()=>setLoading(false));};
 useEffect(()=>{load();try{const value=JSON.parse(localStorage.getItem('aizen-map-saved')||'[]');if(Array.isArray(value)&&value.every(x=>typeof x==='string'))setSaved(value);}catch{setStorageError('Saved picks are unavailable in this browser. You can still save for this visit.');}},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{if(detail)dialog.current?.showModal();else dialog.current?.close();},[detail]);
 useEffect(()=>{if(info)infoDialog.current?.showModal();else infoDialog.current?.close();},[info]);
 const save=(id:string)=>{const next=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];setSaved(next);setToast(next.includes(id)?'Added to saved picks':'Removed from saved picks');try{localStorage.setItem('aizen-map-saved',JSON.stringify(next));}catch{setStorageError('Browser storage is unavailable. Picks are saved only for this visit.');}};
 const matches=(p:Listing,q:string)=>`${p.title} ${p.neighbourhood} ${p.address} ${p.tag} ${p.searchTerms||''} ${categories[p.category]}`.toLowerCase().includes(q.toLowerCase());
 const filtered=useMemo(()=>{if(nearby?.coords)return items.filter(p=>p.coords&&kmBetween(nearby.coords!,p.coords)<=8&&(!p.date||p.date>=today&&p.date<=lastDate)).sort((a,b)=>kmBetween(nearby.coords!,a.coords!)-kmBetween(nearby.coords!,b.coords!));return items.filter(p=>{if(savedOnly&&!saved.includes(p.id))return false;if(query.trim())return matches(p,query.trim());if(category!=='all'&&p.category!==category)return false;if(area!=='all'&&p.neighbourhood!==area)return false;if(p.date&&(p.date<today||p.date>lastDate||day!=='all'&&p.date!==day))return false;if(mode==='all')return true;if(mode==='explore')return placeCategories.includes(p.category);return eventCategories.includes(p.category)&&!!p.date;});},[items,savedOnly,saved,query,category,area,mode,day,today,lastDate,nearby]);
 const suggestions=useMemo(()=>query.trim()?items.filter(p=>matches(p,query.trim())).slice(0,6):[],[items,query]);
 const active=filtered.find(p=>p.id===selected)||null;
 const select=(id:string,fromMap=false)=>{setSelected(id);if(fromMap){setMobileMap(false);setTimeout(()=>{document.getElementById(`card-${id}`)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'});document.getElementById(`select-${id}`)?.focus({preventScroll:true});},80);}};
 const chooseSuggestion=(p:Listing)=>{setNearby(null);setQuery(p.title);setMode(p.date?'tonight':'explore');setCategory('all');setArea('all');setSavedOnly(false);setSearchOpen(false);setSelected(p.id);searchRef.current?.blur();setTimeout(()=>document.getElementById(`card-${p.id}`)?.scrollIntoView({behavior:'smooth',block:'nearest'}),40);};
 const reset=()=>{setNearby(null);setQuery('');setArea('all');setCategory('all');setDay('all');setSavedOnly(false);setSelected(null);};
 const showNearby=(p:Listing)=>{if(!p.coords)return;setNearby(p);setSelected(p.id);setDetail(null);setQuery('');setSavedOnly(false);setMobileMap(false);setTimeout(()=>document.getElementById('feed')?.scrollIntoView({behavior:'smooth',block:'start'}),40);};
 const categoriesForMode=mode==='tonight'?eventCategories:mode==='explore'?placeCategories:[...placeCategories,...eventCategories];
 const areas=[...new Set(items.filter(p=>p.neighbourhood!=='Citywide').map(p=>p.neighbourhood))].sort();
 return <div className="app-shell">
 <a className="skip" href="#feed">Skip to discoveries</a>
 <header className="site-header"><a className="brand" href="/" aria-label="Aizen Map home">Aizen<span> Map</span><span className="brand-dot">✳</span></a><nav className="header-nav" aria-label="Main navigation"><button onClick={()=>{setMode('explore');setQuery('');document.getElementById('feed')?.scrollIntoView({behavior:'smooth'});}}>Discover</button><button onClick={()=>setInfo('about')}>About</button><button onClick={()=>setInfo('sources')}>Sources</button></nav><div className="header-right"><a className="city-link" href="https://www.google.com/maps/dir/?api=1&destination=Bengaluru%2C%20Karnataka" target="_blank" rel="noreferrer" aria-label="Directions to Bengaluru"><Navigation size={15}/> Directions</a><span className="city"><MapPin size={15}/> Bengaluru</span><button className={`saved-nav ${savedOnly?'on':''}`} onClick={()=>setSavedOnly(!savedOnly)} aria-label={`Saved picks, ${saved.length} saved`} aria-pressed={savedOnly}><Bookmark size={18}/> <span>Saved</span><b>{saved.length}</b></button><button className="menu-trigger" aria-label="Open menu" aria-expanded={menuOpen} onClick={()=>setMenuOpen(!menuOpen)}><Menu size={22}/></button></div>{menuOpen&&<nav className="mobile-menu-panel" aria-label="Mobile navigation"><button onClick={()=>{setMode('explore');setQuery('');setMenuOpen(false);}}>Discover places</button><button onClick={()=>{setInfo('about');setMenuOpen(false);}}>About Aizen Map</button><button onClick={()=>{setInfo('sources');setMenuOpen(false);}}>Sources</button><a href="https://www.google.com/maps/dir/?api=1&destination=Bengaluru%2C%20Karnataka" target="_blank" rel="noreferrer">Directions to Bengaluru</a></nav>}</header>
 <div className="workspace"><section className={`feed-panel ${mobileMap?'phone-hide':''}`}>
 <div className="intro"><div className="eyebrow"><span/> THE CITY IS CALLING</div><h1>Less scrolling.<br/>More <span>stepping out.<svg viewBox="0 0 300 15" aria-hidden="true"><path d="M3 10Q150 -3 295 8"/></svg></span></h1><p>Find a place, a screening, or tonight’s next good plan.</p></div>
 <div className="mode-switch" aria-label="Discovery mode"><button aria-pressed={mode==='all'} className={mode==='all'?'selected':''} onClick={()=>{setNearby(null);setMode('all');setCategory('all');setQuery('');}}>✳ All <span>Places & events</span></button><button aria-pressed={mode==='tonight'} className={mode==='tonight'?'selected':''} onClick={()=>{setMode('tonight');setCategory('all');setQuery('');}}><Moon size={17}/> Tonight <span>Events through {dateLabel(lastDate)}</span></button><button aria-pressed={mode==='explore'} className={mode==='explore'?'selected':''} onClick={()=>{setMode('explore');setCategory('all');setQuery('');}}><Sun size={18}/> Explore <span>Food, cafés & malls</span></button></div>
 <div className="search-wrap"><div className="search-box"><Search size={19}/><input ref={searchRef} role="combobox" aria-label="Search places and events" aria-expanded={searchOpen&&!!query} aria-controls="search-suggestions" autoComplete="off" placeholder="Search Starbucks, a film, Indiranagar…" value={query} onFocus={()=>setSearchOpen(true)} onChange={e=>{setNearby(null);setQuery(e.target.value);setSearchOpen(true);}} onKeyDown={e=>{if(e.key==='Enter'){setSearchOpen(false);searchRef.current?.blur();}if(e.key==='Escape')setSearchOpen(false);if(e.key==='ArrowDown'&&suggestions.length){e.preventDefault();document.getElementById('suggestion-0')?.focus();}}}/><button className="search-submit" aria-label="Search listings" onClick={()=>{setSearchOpen(false);searchRef.current?.blur();}}>Search</button>{query&&<button aria-label="Clear search" onClick={()=>{setQuery('');searchRef.current?.focus();}}><X size={16}/></button>}</div>{searchOpen&&query.trim()&&<div id="search-suggestions" className="suggestions" role="listbox" aria-label="Search suggestions">{suggestions.length?suggestions.map((p,i)=>{const Icon=icons[p.category];return <button role="option" aria-selected="false" id={`suggestion-${i}`} key={p.id} onClick={()=>chooseSuggestion(p)} onKeyDown={e=>{if(e.key==='Escape'){setSearchOpen(false);searchRef.current?.focus();}if(e.key==='ArrowDown'){e.preventDefault();document.getElementById(`suggestion-${Math.min(i+1,suggestions.length-1)}`)?.focus();}if(e.key==='ArrowUp'){e.preventDefault();if(i===0)searchRef.current?.focus();else document.getElementById(`suggestion-${i-1}`)?.focus();}}}><Icon size={17}/><span><strong>{p.title}</strong><small>{p.neighbourhood} · {categories[p.category]}</small></span><ArrowUpRight size={16}/></button>}):<p>No matching places or events. Try another name or neighbourhood.</p>}</div>}</div>
 <div className="category-row"><button className={category==='all'?'chosen':''} onClick={()=>{setNearby(null);setCategory('all');}} aria-pressed={category==='all'}>✳ All categories</button>{categoriesForMode.map(c=>{const Icon=icons[c];return <button key={c} className={category===c?'chosen':''} aria-pressed={category===c} onClick={()=>{setNearby(null);setCategory(c);}}><Icon size={16}/>{categories[c]}</button>;})}{mode!=='tonight'&&<button disabled title="Requires an official Google Places integration" aria-label="4+ rating filter unavailable until Google Places is connected">★ 4+ ratings · soon</button>}</div>
 <div className="filter-row"><button className="use-location" onClick={useMyLocation}><MapPin size={15}/> Near me</button><label><MapPin size={15}/><select aria-label="Neighbourhood" value={area} onChange={e=>{const value=e.target.value;setQuery('');setArea(value);const anchor=items.find(p=>p.neighbourhood===value&&p.coords);setNearby(anchor?{...anchor,title:value+' area'}:null);}}><option value="all">All neighbourhoods</option>{areas.map(a=><option key={a}>{a}</option>)}</select></label>{mode!=='explore'&&<label><Clock size={15}/><select aria-label="Event date" value={day} onChange={e=>{setNearby(null);setDay(e.target.value);}}><option value="all">Today + next 2 days</option><option value={today}>Today · {dateLabel(today)}</option><option value={dateOffset(1)}>Tomorrow · {dateLabel(dateOffset(1))}</option><option value={lastDate}>{dateLabel(lastDate)}</option></select></label>}</div>
 <div className="feed-heading"><h2>{nearby?'Around '+nearby.neighbourhood:savedOnly?'Your little shortlist':query?'Search results':mode==='tonight'?'Good plans, great company.':mode==='explore'?'Find your new regular.':'All around Bengaluru.'}</h2><span aria-live="polite">{filtered.length} picks</span></div>
 {nearby&&<div className="nearby-banner"><span>Within 8 km of <strong>{nearby.title}</strong> · all categories</span><button onClick={()=>setNearby(null)}>Clear nearby <X size={14}/></button></div>}<p className="demo-note"><span>CURATED PREVIEW</span> Venue and event links are sourced; check details before going. Ratings need the official Places API.</p>
 {storageError&&<p className="error" role="status">{storageError}</p>}{locationError&&<p className="error" role="status">{locationError}</p>}
 <div id="feed" className="cards" tabIndex={-1}>{loading?<div className="skeleton" role="status">Loading your city guide…</div>:error?<div className="empty" role="alert"><h3>Let’s try that again.</h3><p>{error}</p><button onClick={load}>Retry</button></div>:filtered.length===0?<div className="empty"><Search size={32}/><h3>Nothing in this corner. Yet.</h3><p>{savedOnly?'Save a few discoveries, or widen your filters.':mode==='tonight'&&!query?'No source-verified events match these dates and filters. Try Explore or another category.':'Try another neighbourhood, category, or search term.'}</p><button onClick={reset}>Reset filters</button></div>:filtered.map((p,i)=>{const Icon=icons[p.category];return <article key={p.id} id={`card-${p.id}`} className={`discovery-card ${p.id===selected?'is-selected':''}`}><div className={`card-image visual-${p.category}`}>{p.image?<img src={p.image} alt="Illustrative image, not this specific venue or event" onError={e=>{e.currentTarget.style.display='none';}}/>:<span className="card-art"><Icon size={58} strokeWidth={1.3}/><small>{p.category==='cafes'?p.title.split(' · ')[0]:categories[p.category].toUpperCase()}</small></span>}<span className={`category-badge ${p.category}`}><Icon size={14}/>{categories[p.category]}</span><button className={`save ${saved.includes(p.id)?'is-saved':''}`} aria-label={`${saved.includes(p.id)?'Unsave':'Save'} ${p.title}`} aria-pressed={saved.includes(p.id)} onClick={()=>save(p.id)}><Bookmark size={19} fill={saved.includes(p.id)?'currentColor':'none'}/></button>{p.image&&<span className="image-caption">ILLUSTRATIVE IMAGE</span>}<span className="card-number">{String(i+1).padStart(2,'0')}</span></div><div className="card-body"><div className="card-meta"><span><MapPin size={13}/>{p.neighbourhood}</span><span>{p.tag}</span></div><button id={`select-${p.id}`} className="card-title" onClick={()=>select(p.id)} aria-pressed={p.id===selected}><h3>{p.title}</h3><ArrowUpRight size={22}/></button><div className="card-bottom"><span><Clock size={14}/>{p.date?`${dateLabel(p.date)} · ${p.time}`:p.hours||'See official source'} {p.date&&<small>· confirm at source</small>}</span><button onClick={()=>{select(p.id);setDetail(p);}} aria-label={`Details for ${p.title}`}>Details <ArrowRight size={16}/></button></div></div></article>;})}</div><footer className="feed-footer"><strong>Aizen Map</strong><span>Places and dated events are manually sourced. This is a preview, not a live listings feed.</span><div className="footer-links"><button onClick={()=>setInfo('about')}>About the app</button><button onClick={()=>setInfo('sources')}>Sources & verification</button><span>Contact: hello@aizenmap.example <em>(placeholder)</em></span></div></footer>
 </section><aside className={`map-panel ${!mobileMap?'phone-hide':''}`}><CityMap items={filtered} selected={active?.id||null} onSelect={id=>{select(id,true);const item=filtered.find(p=>p.id===id);if(item)setDetail(item);}}/><div className="map-top"><span><MapPin size={16}/> Bengaluru, a little closer.</span><b>{filtered.filter(p=>p.coords).length} PINS</b></div><div className="map-bottom"><div className="map-callout"><span className="map-callout-icon">✳</span><div><strong>{active?active.title:'Good things are all around.'}</strong><p>{active?`${active.neighbourhood} · ${active.coords?'approximate map pin':'official branch finder'}`:'Scroll over the map to zoom. Tap a pin for details.'}</p></div>{active&&<button aria-label="Show nearby places and events" title="Show nearby places and events" onClick={()=>showNearby(active)}><MapPin size={20}/></button>}</div><div className="map-legend">{categoriesForMode.map(c=><span key={c}><i className={c}/>{categories[c]}</span>)}<span>Approximate pins · © OpenStreetMap</span></div></div></aside></div>
 <button className="mobile-view" onClick={()=>setMobileMap(!mobileMap)}>{mobileMap?<List size={18}/>:<MapIcon size={18}/>} {mobileMap?'Show feed':'Explore map'} <span>{filtered.length}</span></button>
 <div className="toast" role="status">{toast&&<><Check size={16}/>{toast}</>}</div>
 <dialog aria-label="Listing details" ref={dialog} onCancel={()=>setDetail(null)} onClick={e=>{if(e.target===e.currentTarget)setDetail(null);}}>{detail&&<div className="detail"><button className="close" autoFocus aria-label="Close details" onClick={()=>setDetail(null)}><X/></button>{detail.image?<img src={detail.image} alt="Illustrative scene, not this specific venue or event"/>:<div className={`detail-art visual-${detail.category}`}>{(()=>{const Icon=icons[detail.category];return <Icon size={66}/>})()}</div>}<div className="detail-body"><span className="eyebrow">{categories[detail.category].toUpperCase()} · SOURCE LINKED</span><h2>{detail.title}</h2><p className="detail-location"><MapPin size={17}/>{detail.address}</p><p>{detail.description}</p><div className="detail-time"><Clock size={19}/><div><strong>{detail.date?`${dateLabel(detail.date)} · ${detail.time}`:detail.hours||'Check current hours with the venue'}</strong><p>{detail.date?'Date from organiser listing. Confirm before attending.':'Hours are not live; check the venue source before visiting.'}</p></div></div><p className="location-note">{detail.coords?'Map pin is approximate. Directions use the named place or venue.':'No branch pin until a current location is verified.'} Ratings are not shown without an official source.</p><div className="detail-actions">{detail.coords&&<button className="directions" onClick={()=>showNearby(detail)}>Around here <MapPin size={17}/></button>}<a className="directions" href={`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(`${detail.title}, ${detail.address}, Bengaluru`)}`} target="_blank" rel="noreferrer">Directions <Navigation size={17}/></a><a className="source-link" href={detail.source} target="_blank" rel="noreferrer">{detail.date?'Book / event page':detail.sourceLabel} <ArrowUpRight size={17}/></a></div>{detail.coords&&<div className="travel-modes"><span>Plan in Google Maps:</span>{([['driving','Car'],['transit','Transit'],['walking','Walk']] as const).map(([mode,label])=><a key={mode} href={'https://www.google.com/maps/dir/?api=1&destination='+encodeURIComponent(detail.title+', '+detail.address+', Bengaluru')+'&travelmode='+mode} target="_blank" rel="noreferrer">{label}</a>)}</div>}<button className="detail-save" onClick={()=>save(detail.id)}><Bookmark size={18}/>{saved.includes(detail.id)?'Saved to your picks':'Save for later'}</button></div></div>}</dialog>
 <dialog aria-label={info==='about'?'About Aizen Map':'Sources and verification'} ref={infoDialog} onCancel={()=>setInfo(null)} onClick={e=>{if(e.target===e.currentTarget)setInfo(null);}}><div className="info-body"><button className="close" autoFocus aria-label="Close" onClick={()=>setInfo(null)}><X/></button><span className="eyebrow">AIZEN MAP</span>{info==='about'?<><h2>Your city, on your terms.</h2><p>Aizen Map is a local Bengaluru discovery preview. Tonight brings dated events from organiser or ticket pages. Explore brings cafés, food places and malls. Choose a card or pin to see where it sits in the city.</p><p>Save a shortlist on this device. The site has no accounts or bookings.</p></>:<><h2>Where these picks come from.</h2><p>Place names and listed hours link to official venue, brand, or mall pages. Event dates link to ticket or screening pages. Details can change, so use the source link in each card before going.</p><p>Ratings and reviews are intentionally absent until official Google Places access is available. Unverified branch finders have no map pin. The OpenStreetMap demo map shows approximate locations with attribution.</p></>}<button className="info-done" onClick={()=>setInfo(null)}>Back to the city <ArrowRight size={18}/></button></div></dialog>
 </div>;
}

