import type {Listing} from './listings';

// Venue and operator pages establish these preview places. Pins are approximate.
export const expandedListings:Listing[]=[
 {id:'beanlore-hsr',title:'Beanlore · HSR Layout',category:'cafes',neighbourhood:'HSR Layout',coords:[12.912,77.641],address:'450, 17th Cross, Sector 4, HSR Layout',tag:'Neighbourhood café',description:'Specialty coffee and food from a Bengaluru-grown café. Check its site for current opening details.',source:'https://www.beanlore.com/',sourceLabel:'Beanlore website'},
 {id:'beanlore-indiranagar',title:'Beanlore · Indiranagar',category:'cafes',neighbourhood:'Indiranagar',coords:[12.978,77.637],address:'503, CMH Road, Indiranagar 1st Stage',tag:'Local coffee',description:'Beanlore lists this Indiranagar branch on its own site. Pin and hours should be confirmed before travel.',source:'https://www.beanlore.com/',sourceLabel:'Beanlore website'},
 {id:'beanlore-jayanagar',title:'Beanlore · Jayanagar',category:'cafes',neighbourhood:'Jayanagar',coords:[12.928,77.586],address:'85, 5th Main Road, Jayanagar',tag:'Local coffee',description:'A Jayanagar branch listed by Beanlore. Check current hours on the café website.',source:'https://www.beanlore.com/',sourceLabel:'Beanlore website'},
 {id:'benki-jayanagar',title:'Benki Coffee · Jayanagar',category:'cafes',neighbourhood:'Jayanagar',coords:[12.925,77.583],address:'Ground floor, 36th A Cross, 9th Main, 5th Block, Jayanagar',hours:'8:00 AM – 10:00 PM per venue website',tag:'Specialty coffee',description:'Independent specialty coffee in Jayanagar with an address and hours on the official website.',source:'https://www.benki.coffee/',sourceLabel:'Benki website'},
 {id:'firefly-jayanagar',title:'Firefly Coffee Roasters',category:'cafes',neighbourhood:'Jayanagar',coords:[12.928,77.58],address:'Jayanagar, Bengaluru; confirm exact entrance with venue',tag:'Local roaster',description:'A neighbourhood specialty roaster in Jayanagar. Pin marks the area rather than a verified entrance.',source:'https://www.fireflycoffeeroasters.com/',sourceLabel:'Firefly website'},
 {id:'diha-jp',title:'DIHA · JP Nagar',category:'cafes',neighbourhood:'JP Nagar',coords:[12.905,77.587],address:'17, 15th Cross Road, JP Nagar 4th Phase',tag:'Coffee & pizza',description:'Specialty coffee, food and an evening setting at a JP Nagar venue. Verify hours on its site.',source:'https://www.diha.cafe/',sourceLabel:'DIHA website'},
 {id:'kind-jp',title:'The Kind · JP Nagar',category:'cafes',neighbourhood:'JP Nagar',coords:[12.907,77.591],address:'JP Nagar, Bengaluru; check venue for exact branch',tag:'Bengaluru roastery',description:'The Kind lists a JP Nagar location. Its website should be checked for the exact address and hours.',source:'https://thekindindia.com/contact/',sourceLabel:'The Kind website'},
 {id:'kind-bellandur',title:'The Kind · Bellandur',category:'cafes',neighbourhood:'Bellandur',coords:[12.928,77.678],address:'Bellandur, Bengaluru; check venue for exact branch',tag:'Bengaluru roastery',description:'A Bellandur location listed by The Kind. Area pin only until the entrance is verified.',source:'https://thekindindia.com/contact/',sourceLabel:'The Kind website'},
 {id:'third-wave-whitefield',title:'Third Wave Coffee · Whitefield',category:'cafes',neighbourhood:'Whitefield',coords:[12.97,77.751],address:'Shop 62, Whitefield Main Road, Prestige Ozone',hours:'10:00 AM – 10:00 PM per brand locator',tag:'Whitefield branch',description:'A separate Whitefield branch from the official Third Wave locator. Confirm current hours before travelling.',source:'https://cafe.thirdwavecoffee.in/location/karnataka/bengaluru?page=2',sourceLabel:'Third Wave locator'},
 {id:'third-wave-banashankari',title:'Third Wave Coffee · Banashankari',category:'cafes',neighbourhood:'Banashankari',coords:[12.925,77.56],address:'30th Main Road, Banashankari 3rd Stage',tag:'South-side coffee',description:'A Banashankari branch listed on the brand’s Bengaluru locator. Pin is approximate.',source:'https://cafe.thirdwavecoffee.in/location/karnataka/bengaluru?page=2',sourceLabel:'Third Wave locator'},
 {id:'third-wave-marathahalli',title:'Third Wave Coffee · Marathahalli',category:'cafes',neighbourhood:'Marathahalli',coords:[12.958,77.697],address:'ITPL Main Road, AECS Layout, Marathahalli',tag:'East-side coffee',description:'Another listed Third Wave branch in the east Bengaluru corridor. Check the brand locator for updates.',source:'https://cafe.thirdwavecoffee.in/location/karnataka/bengaluru?page=2',sourceLabel:'Third Wave locator'},
 {id:'gopalan-innovation',title:'Gopalan Innovation Mall',category:'malls',neighbourhood:'JP Nagar',coords:[12.918,77.601],address:'Bannerghatta Road, JP Nagar 3rd Phase',tag:'Mall & cinema',description:'A smaller JP Nagar area mall with Gopalan Cinemas and bowling, according to the operator. Check cinema listings separately for sessions.',source:'https://www.gopalanmall.com/gopalan-innovation-mall.html',sourceLabel:'Gopalan Mall page'},
 {id:'gopalan-signature',title:'Gopalan Signature Mall',category:'malls',neighbourhood:'Old Madras Road',coords:[12.996,77.661],address:'Old Madras Road, near Benniganahalli Metro',tag:'Mall & cinema',description:'An Old Madras Road neighbourhood mall with dining and cinema listed by the operator.',source:'https://www.gopalanmall.com/gopalan-signature-mall.html',sourceLabel:'Gopalan Mall page'},
 {id:'gopalan-cinemas',title:'Gopalan Cinemas · Innovation Mall',category:'cinema',neighbourhood:'JP Nagar',coords:[12.9182,77.6012],address:'Inside Gopalan Innovation Mall, Bannerghatta Road',tag:'Find a screening',description:'The cinema is listed by the mall operator; film showtimes are not seeded. Open the cinema page for current sessions and booking options.',source:'https://www.gopalanmall.com/gopalan-cinemas.html',sourceLabel:'Gopalan Cinemas',searchTerms:'inox theatre movie showtimes tickets'},
 {id:'kfc-jayanagar',title:'KFC · Jayanagar',category:'food',neighbourhood:'Jayanagar',coords:[12.929,77.584],address:'149/40/1, 32nd C Cross, 11th Main, 4th Block',tag:'Jayanagar branch',description:'A separate Jayanagar branch listed on the official KFC locator.',source:'https://restaurants.kfc.co.in/location/karnataka/bangalore/jayanagar',sourceLabel:'KFC locator'},
 {id:'kfc-shantiniketan',title:'KFC · Nexus Shantiniketan',category:'food',neighbourhood:'Whitefield',coords:[12.9894,77.7263],address:'Level 3, Nexus Shantiniketan, Whitefield',tag:'Inside a mall',description:'The official KFC locator lists this Whitefield mall branch. Check current opening hours there.',source:'https://restaurants.kfc.co.in/location/karnataka/bangalore/whitefield',sourceLabel:'KFC locator'},
 {id:'dominos-hsr',title:'Domino’s · HSR Layout',category:'food',neighbourhood:'HSR Layout',coords:[12.914,77.638],address:'1573, ground floor, HSR Layout, Bengaluru',tag:'Pizza stop',description:'A separate HSR Layout branch on the Domino’s restaurant site. Verify hours and availability before going.',source:'https://www.dominos.co.in/store-locations/bangalore/hsr-layouts/reviews',sourceLabel:'Domino’s store page'},
 {id:'mantri-square',title:'Mantri Square',category:'malls',neighbourhood:'Malleshwaram',coords:[12.991,77.571],address:'Sampige Road, Malleshwaram',tag:'Metro-side mall',description:'Shopping, food court and cinema beside the metro. Check the mall site for the current lineup.',source:'https://www.mantrisquare.com/entertainment.php',sourceLabel:'Mantri Square website'},
 {id:'garuda-mall',title:'Garuda Mall',category:'malls',neighbourhood:'Magrath Road',coords:[12.97,77.611],address:'Magrath Road, Ashok Nagar',tag:'Central shopping',description:'A central Bengaluru mall with dining and cinema listed on its website.',source:'https://www.garudamall.in/',sourceLabel:'Garuda Mall website'},
 {id:'rmz-galleria',title:'RMZ Galleria Mall',category:'malls',neighbourhood:'Yelahanka',coords:[13.095,77.593],address:'Yelahanka, north Bengaluru',tag:'North-side mall',description:'A Yelahanka mall with shopping, food and entertainment on its official site.',source:'https://www.rmzgalleriamall.com/',sourceLabel:'RMZ Galleria website'},
 {id:'royal-meenakshi',title:'Royal Meenakshi Mall',category:'malls',neighbourhood:'Hulimavu',coords:[12.879,77.598],address:'Bannerghatta Road, Hulimavu',tag:'South-side mall',description:'A shopping and cinema destination along Bannerghatta Road. Check the mall website before visiting.',source:'https://royalmeenakshimall.com/',sourceLabel:'Mall website'},
 {id:'inox-jp-central',title:'INOX · Central JP Nagar',category:'cinema',neighbourhood:'JP Nagar',coords:[12.915,77.583],address:'5th floor, Central, 45th Cross, JP Nagar 2nd Phase',tag:'Find a movie',description:'Cinema venue listed by BookMyShow. Current film sessions and seats must be checked on the booking site.',source:'https://in.bookmyshow.com/explore/movies-bengaluru',sourceLabel:'Movie booking site'},
 {id:'cinepolis-shantiniketan',title:'Cinépolis · Nexus Shantiniketan',category:'cinema',neighbourhood:'Whitefield',coords:[12.9896,77.7264],address:'Inside Nexus Shantiniketan, Whitefield',tag:'Find a movie',description:'A Whitefield cinema venue; check the linked cinema service for current showtimes and booking.',source:'https://in.bookmyshow.com/explore/movies-bengaluru',sourceLabel:'Movie booking site'},
 {id:'pvr-vega',title:'PVR · Nexus Vega City',category:'cinema',neighbourhood:'JP Nagar',coords:[12.9074,77.6014],address:'Inside Nexus Vega City, Bannerghatta Road',tag:'Find a movie',description:'A JP Nagar area cinema; use the booking site for current films and seats.',source:'https://in.bookmyshow.com/explore/movies-bengaluru',sourceLabel:'Movie booking site'},
 {id:'cinepolis-meenakshi',title:'Cinépolis · Royal Meenakshi Mall',category:'cinema',neighbourhood:'Hulimavu',coords:[12.8793,77.5983],address:'Inside Royal Meenakshi Mall, Bannerghatta Road',tag:'Find a movie',description:'The cinema venue is listed by BookMyShow. Current showtimes must be checked before booking.',source:'https://in.bookmyshow.com/explore/movies-bengaluru',sourceLabel:'Movie booking site'}
];
