import type {Listing} from './listings';

// Source-linked discovery venues. These are not claims of a screening or match today.
// Coordinates mark an approximate area; the linked venue or operator has current details.
export const freshListings:Listing[]=[
 {id:'araku-indiranagar',title:'ARAKU Coffee · Indiranagar',category:'cafes',neighbourhood:'Indiranagar',coords:[12.9783,77.6372],address:'12th Main Road, HAL 2nd Stage, Indiranagar',hours:'8:00 AM – 11:00 PM per venue site',tag:'Coffee & a slow date',description:'A Bengaluru flagship for specialty coffee and food. Check the venue page for current hours and reservations.',source:'https://www.arakucoffee.in/pages/bangalore',sourceLabel:'ARAKU venue page'},
 {id:'araku-ashok-nagar',title:'ARAKU Coffee · Ashok Nagar',category:'cafes',neighbourhood:'Ashok Nagar',coords:[12.968,77.608],address:'Ashok Nagar, Bengaluru; confirm the entrance with ARAKU',hours:'8:00 AM – 8:00 PM per venue locator',tag:'Central coffee',description:'A second Bengaluru ARAKU location shown on the brand locator. The pin marks the area until its entrance is confirmed.',source:'https://www.arakucoffee.in/pages/locations',sourceLabel:'ARAKU locations'},
 {id:'lavonne-domlur',title:'Lavonne Café · Domlur',category:'cafes',neighbourhood:'Domlur',coords:[12.96,77.637],address:'#263, 3rd Cross, Domlur 2nd Stage',tag:'Pastry & coffee',description:'The academy lists a ground-floor café at its Domlur campus. Confirm café access and hours with the venue.',source:'https://lavonne.in/contact',sourceLabel:'Lavonne contact page'},
 {id:'pvr-orion-uptown',title:'PVR · Orion Uptown',category:'cinema',neighbourhood:'Old Madras Road',coords:[13.0221,77.7291],address:'Second floor, Orion Uptown Mall, Old Madras Road',tag:'Find a screening',description:'The mall lists PVR on its second floor. This is a cinema finder, not a confirmed film session; check current titles and seats with the operator.',source:'https://www.orionmalls.com/orion-uptown-mall/searchpage/',sourceLabel:'Orion Uptown directory'},
 {id:'bww-indiranagar',title:'Buffalo Wild Wings · Indiranagar',category:'sports',neighbourhood:'Indiranagar',coords:[12.979,77.641],address:'Indiranagar, Bengaluru; confirm branch entrance',tag:'Sports-screening venue',description:'A place to check for match screenings with friends. No game or watch party is confirmed in this preview; consult the venue schedule before travelling.',source:'https://buffalowildwings.in/nearby_stores',sourceLabel:'Buffalo Wild Wings locations',searchTerms:'live match cricket football F1 watch party'},
 {id:'bww-phoenix',title:'Buffalo Wild Wings · Phoenix Marketcity',category:'sports',neighbourhood:'Mahadevapura',coords:[12.9979,77.6969],address:'Phoenix Marketcity, Whitefield Main Road, Mahadevapura',tag:'Sports-screening venue',description:'An east-side venue to check for a live screening. The preview does not assert that a particular match is scheduled.',source:'https://buffalowildwings.in/nearby_stores',sourceLabel:'Buffalo Wild Wings locations',searchTerms:'live match cricket football F1 watch party'}
];
