import {moreListings} from './moreListings';
import {expandedListings} from './expandedListings';
import {freshListings} from './freshListings';
export type Category='cafes'|'food'|'malls'|'cinema'|'sports'|'gigs';
export type Listing={id:string;title:string;category:Category;neighbourhood:string;address:string;description:string;tag:string;source:string;sourceLabel:string;coords?:[number,number];image?:string;hours?:string;date?:string;time?:string;searchTerms?:string};
export const categories:Record<Category,string>={cafes:'Cafés',food:'Food',malls:'Malls',cinema:'Screenings',sports:'Watch parties',gigs:'Live gigs'};
export const listings:Listing[]=[
{id:'third-wave-indiranagar',title:'Third Wave Coffee · 12th Main',category:'cafes',neighbourhood:'Indiranagar',coords:[12.9776,77.6353],address:'12th Main Road, HAL 2nd Stage, Indiranagar',hours:'8:00 AM – 11:00 PM',tag:'Morning to night',description:'A café on 12th Main for an early coffee or evening catch-up. Hours are from the café’s listing; check before leaving.',source:'https://cafe.thirdwavecoffee.in/coffee-cafe-12th-main-indiranagar-bengaluru-29962/home',sourceLabel:'Third Wave store page'},
{id:'starbucks-indiranagar',title:'Starbucks · Indiranagar',category:'cafes',neighbourhood:'Indiranagar',coords:[12.978,77.639],address:'945, 12th Main Road, HAL 2nd Stage, Indiranagar',hours:'8:00 AM – 11:00 PM',tag:'Coffee & catch-ups',description:'A coffee stop on 12th Main. Hours come from the official store page and may change.',source:'https://stores.starbucks.in/store-pages/starbucks-bangalore-3/',sourceLabel:'Starbucks store page'},
{id:'third-wave-koramangala',title:'Third Wave Coffee · Koramangala',category:'cafes',neighbourhood:'Koramangala',coords:[12.9336,77.6207],address:'984, 80 Feet Road, 4th Block, Koramangala',hours:'8:00 AM – 1:00 AM',tag:'Late coffee',description:'A later-opening Koramangala café according to its official listing. Confirm hours before travelling.',source:'https://cafe.thirdwavecoffee.in/coffee-cafe-koramangala-bengaluru-29964/home',sourceLabel:'Third Wave store page'},
{id:'cafe-77-east',title:'Café 77 East · Taj Bangalore',category:'cafes',neighbourhood:'Airport',coords:[13.2008,77.7085],address:'Taj Bangalore, opposite Kempegowda International Airport',hours:'24/7 per hotel website',tag:'Around the clock',description:'All-day dining near the airport. The hotel states 24/7 service; check access and current hours first.',source:'https://www.tajhotels.com/en-in/hotels/taj-bangalore/restaurants/cafe-77-east?hotelId=31aea616-8fd2-46c6-acdc-589a37b0ed3f',sourceLabel:'Taj restaurant page'},
{id:'kfc-koramangala',title:'KFC · 4th Block',category:'food',neighbourhood:'Koramangala',coords:[12.9337,77.6256],address:'35, 7th Main, 80 Feet Road, Koramangala',tag:'Quick bite',description:'A Koramangala branch listed by KFC. Check its locator for today’s hours.',source:'https://restaurants.kfc.co.in/location/karnataka/bangalore/koramangala',sourceLabel:'KFC restaurant locator'},
{id:'dominos-mg',title:'Domino’s · MG Road',category:'food',neighbourhood:'Church Street',coords:[12.9755,77.6068],address:'MG Road Metro Station, Church Street side entrance',hours:'11:00 AM – 11:00 PM per locator',tag:'Pizza stop',description:'A Domino’s branch beside the MG Road metro. Confirm current hours on the brand locator.',source:'https://www.dominos.co.in/store-location/',sourceLabel:'Domino’s store locator'},
{id:'mcd-koramangala',title:'McDonald’s · Koramangala',category:'food',neighbourhood:'Koramangala',coords:[12.936,77.616],address:'JNC Koramangala area, Bengaluru',tag:'Quick bite',description:'McDonald’s lists a JNC Koramangala restaurant. This pin is approximate; confirm the exact branch and hours on the locator.',source:'https://mcdonaldsindia.com/googlemap.php?state=Karnataka',sourceLabel:'McDonald’s restaurant locator'},
{id:'ccd-finder',title:'Café Coffee Day · find a café',category:'cafes',neighbourhood:'Citywide',address:'Choose a Bengaluru branch in the official finder',tag:'Branch finder',description:'CCD’s café finder is the source for branches. No current branch or hours have been verified, so this shortcut has no map pin.',source:'https://www.cafecoffeeday.com/',sourceLabel:'CCD café finder',searchTerms:'CCD coffee day'},
{id:'popeyes-finder',title:'Popeyes · find a restaurant',category:'food',neighbourhood:'Citywide',address:'Choose a Bengaluru branch on the official site',tag:'Branch finder',description:'Explore Popeyes locations using its official site. No individual branch or hours are claimed here, so this shortcut has no map pin.',source:'https://www.popeyes.in/',sourceLabel:'Popeyes India',searchTerms:'chicken sandwich'},
{id:'orion',title:'Orion Mall · Brigade Gateway',category:'malls',neighbourhood:'Rajajinagar',coords:[13.0123,77.5549],address:'Dr Rajkumar Road, Rajajinagar, Bengaluru',tag:'Shop & wander',description:'A shopping and dining destination at Brigade Gateway. Check its site for individual brand hours and events.',source:'https://www.orionmalls.com/orion-mall-at-brigade-gateway/mall-map',sourceLabel:'Orion Mall map'},
{id:'phoenix',title:'Phoenix Marketcity',category:'malls',neighbourhood:'Mahadevapura',coords:[12.9978,77.6968],address:'Whitefield Main Road, Mahadevapura, Bengaluru',tag:'Mall day',description:'A large retail destination in east Bengaluru. Stores and cinema sessions have separate schedules.',source:'https://www.phoenixmarketcity.com/bangalore',sourceLabel:'Phoenix Marketcity'},
{id:'lahe-lahe',title:'Music Jam by Lahe Lahe Caravan',category:'gigs',neighbourhood:'Indiranagar',coords:[12.979,77.64],address:'Dhurii, Indiranagar, Bengaluru',date:'2026-09-23',time:'7:30 PM',tag:'Community jam',description:'A participatory Wednesday music jam listed for 23 September. Check the ticket page for availability and exact venue. Pin is approximate.',source:'https://in.bookmyshow.com/events/music-jam-by-lahe-lahe-caravan/ET00509341',sourceLabel:'BookMyShow event page'},
{id:'hard-rock-karaoke',title:'Live Band Karaoke with KJ Marcel',category:'gigs',neighbourhood:'St Marks Road',coords:[12.9718,77.6015],address:'Hard Rock Cafe, Bengaluru',date:'2026-09-23',time:'8:00 PM',tag:'Sing with a band',description:'Live-band karaoke listed for Wednesday 23 September. Follow the source for tickets and exact venue.',source:'https://in.bookmyshow.com/events/live-band-karaoke/ET00487674',sourceLabel:'BookMyShow event page'},
{id:'my-hustler',title:'My Hustler (1966)',category:'cinema',neighbourhood:'Cox Town',coords:[13.0025,77.616],address:'Angala, Cox Town, Bengaluru',date:'2026-09-24',time:'7:45 PM',tag:'Film club screening',image:'/images/cinema.jpg',description:'A film-club screening listed by Fillum for 24 September. Check tickets and venue details. Pin is approximate.',source:'https://fillum.in/film-screenings-in-bangalore',sourceLabel:'Fillum screening page'},
{id:'sila-jam',title:'SILAA Thursday Kannada Jamming',category:'gigs',neighbourhood:'Malleshwaram',coords:[13.006,77.568],address:'Silaa The Garden Cafe, Malleshwaram',date:'2026-09-24',time:'6:00 PM',tag:'Kannada retro',description:'A Kannada music session listed for Thursday 24 September. Confirm tickets and details on the event page.',source:'https://in.bookmyshow.com/events/pavan-bhat-live-kannada-jamming/ET00452555/',sourceLabel:'BookMyShow event page'},
{id:'ragam-jam',title:'Sandalwood + Bollywood Live Jamming',category:'gigs',neighbourhood:'Bengaluru South',coords:[12.912,77.626],address:'The Ragam Cafe, Bengaluru',date:'2026-09-24',time:'6:00 PM',tag:'Live jamming',description:'An evening of Kannada and Hindi songs listed for 24 September. Pin is approximate; check the source for exact location.',source:'https://in.bookmyshow.com/events/sandalwood-bollywood-live-jamming/ET00518177',sourceLabel:'BookMyShow event page'},
{id:'baithaki',title:'Baithaki Mehfil · Sufi Night',category:'gigs',neighbourhood:'Bellandur',coords:[12.925,77.678],address:'Radio Bar, RMZ Ecoworld, Bellandur',date:'2026-09-25',time:'8:30 PM',tag:'Sufi night',description:'A Sufi music night listed for Friday 25 September. Tickets and final details are on the source page.',source:'https://in.bookmyshow.com/events/baithaki-mehfil/ET00517466',sourceLabel:'BookMyShow event page'},
{id:'rajasthan',title:'Sounds of Rajasthan · A Sufi Evening',category:'gigs',neighbourhood:'Bengaluru South',coords:[12.915,77.605],address:'The Sabha, Bengaluru',date:'2026-09-25',time:'7:30 PM',tag:'Folk & Sufi',description:'The Langa Brothers are listed for 25 September. Check the source for tickets and the exact venue.',source:'https://in.bookmyshow.com/events/sounds-of-rajasthan-a-sufi-evening/et1ll19d7f',sourceLabel:'BookMyShow event page'}
, ...moreListings, ...expandedListings, ...freshListings];
export interface ListingProvider{getListings(signal?:AbortSignal):Promise<Listing[]>}
export const demoProvider:ListingProvider={async getListings(){return listings}};
export const localISODate=(date=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
export const dateOffset=(days:number)=>{const d=new Date();d.setUTCDate(d.getUTCDate()+days);return localISODate(d)};

