import type {Listing} from './listings';

// Directory-backed demo picks. Mall tenants and opening hours can change; verify at source.
export const moreListings:Listing[]=[
 {id:'mall-of-asia',title:'Phoenix Mall of Asia',category:'malls',neighbourhood:'Hebbal',coords:[13.063,77.592],address:'Bellary Road, Byatarayanapura, North Bengaluru',tag:'Airport corridor',description:'A north Bengaluru mall on the airport road. Browse its official site for the current dining and events lineup. Pin is approximate.',source:'https://www.phoenixmallofasia.com/',sourceLabel:'Mall website'},
 {id:'bhartiya-mall',title:'Bhartiya Mall of Bengaluru',category:'malls',neighbourhood:'Thanisandra',coords:[13.083,77.625],address:'Bhartiya City, Thanisandra Main Road, Bengaluru',tag:'North Bengaluru',description:'Shopping and dining at Bhartiya City. The mall publishes a dedicated Eat & Drink directory; check it for current tenants and hours.',source:'https://bhartiyamallofbengaluru.com/eat-and-drink/',sourceLabel:'Mall dining directory'},
 {id:'bhartiya-dining',title:'Eat & Drink · Bhartiya Mall',category:'food',neighbourhood:'Thanisandra',coords:[13.0832,77.6252],address:'Inside Bhartiya Mall, Bhartiya City, Thanisandra',tag:'Inside a mall',description:'Explore the mall’s listed restaurants, cafés and food options together. Individual tenants and hours can change; use the official directory.',source:'https://bhartiyamallofbengaluru.com/eat-and-drink/',sourceLabel:'Mall dining directory',searchTerms:'food court cafe restaurants'},
 {id:'orion-uptown',title:'Orion Uptown Mall',category:'malls',neighbourhood:'Old Madras Road',coords:[13.022,77.729],address:'Old Madras Road, Sannatammanahalli, Bengaluru',tag:'East Bengaluru',description:'An east-side mall with a listed food court and several dining options. Confirm the current tenant lineup on its directory.',source:'https://www.orionmalls.com/orion-uptown-mall/searchpage/',sourceLabel:'Orion Uptown directory'},
 {id:'kamat-uptown',title:'Kamat Hosaruchi · Orion Uptown',category:'food',neighbourhood:'Old Madras Road',coords:[13.0222,77.7292],address:'Second floor, Orion Uptown Mall, Old Madras Road',tag:'Inside a mall',description:'South Indian food listed in Orion Uptown’s directory. Check the mall listing for current availability and hours.',source:'https://www.orionmalls.com/orion-uptown-mall/searchpage/',sourceLabel:'Orion Uptown directory'},
 {id:'haldirams-uptown',title:'Haldiram’s · Orion Uptown',category:'food',neighbourhood:'Old Madras Road',coords:[13.0218,77.7288],address:'Second floor, Orion Uptown Mall, Old Madras Road',tag:'Inside a mall',description:'A food option listed by Orion Uptown. Verify the current tenant and hours before visiting.',source:'https://www.orionmalls.com/orion-uptown-mall/searchpage/',sourceLabel:'Orion Uptown directory'},
 {id:'nexus-koramangala',title:'Nexus Koramangala',category:'malls',neighbourhood:'Koramangala',coords:[12.934,77.611],address:'Hosur Road, Koramangala, Bengaluru',tag:'Shop & eat',description:'A Koramangala mall with a wide dining directory. Use the linked centre listing to check the current food options.',source:'https://www.scai.in/portfolio/nexus-koramangala-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'california-burrito-nexus',title:'California Burrito · Nexus Koramangala',category:'food',neighbourhood:'Koramangala',coords:[12.9342,77.6112],address:'Inside Nexus Koramangala, Hosur Road',tag:'Inside a mall',description:'Listed in the mall’s food-service directory. Check the centre for current hours and availability.',source:'https://www.scai.in/portfolio/nexus-koramangala-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'chai-point-nexus',title:'Chai Point · Nexus Koramangala',category:'cafes',neighbourhood:'Koramangala',coords:[12.9338,77.6108],address:'Inside Nexus Koramangala, Hosur Road',tag:'Tea break',description:'A tea and snack stop listed in the centre directory. Tenant and hours may change.',source:'https://www.scai.in/portfolio/nexus-koramangala-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'nexus-shantiniketan',title:'Nexus Shantiniketan',category:'malls',neighbourhood:'Whitefield',coords:[12.989,77.726],address:'ITPL Main Road, Whitefield, Bengaluru',tag:'Whitefield day out',description:'A Whitefield mall with an extensive published food-service list. Check current mall information before going.',source:'https://www.scai.in/portfolio/nexus-shantiniketan-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'third-wave-shantiniketan',title:'Third Wave Coffee · Nexus Shantiniketan',category:'cafes',neighbourhood:'Whitefield',coords:[12.9892,77.7262],address:'Inside Nexus Shantiniketan, Whitefield',tag:'Inside a mall',description:'Listed in the mall food-service directory. Confirm this branch and its hours before visiting.',source:'https://www.scai.in/portfolio/nexus-shantiniketan-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'lavonne-shantiniketan',title:'Lavonne · Nexus Shantiniketan',category:'cafes',neighbourhood:'Whitefield',coords:[12.9888,77.7258],address:'Inside Nexus Shantiniketan, Whitefield',tag:'Bakery stop',description:'A bakery option listed in the centre directory. Verify current hours with the venue.',source:'https://www.scai.in/portfolio/nexus-shantiniketan-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'nexus-whitefield',title:'Nexus Whitefield',category:'malls',neighbourhood:'Whitefield',coords:[12.959,77.746],address:'Whitefield Main Road, Bengaluru',tag:'East-side wander',description:'A Whitefield shopping destination with dining options in the centre directory.',source:'https://www.scai.in/portfolio/nexus-whitefield-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'biryani-blues-whitefield',title:'Biryani Blues · Nexus Whitefield',category:'food',neighbourhood:'Whitefield',coords:[12.9592,77.7462],address:'Inside Nexus Whitefield, Whitefield Main Road',tag:'Inside a mall',description:'Listed in the mall food-service directory. Check current availability before visiting.',source:'https://www.scai.in/portfolio/nexus-whitefield-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'nexus-vega-city',title:'Nexus Vega City',category:'malls',neighbourhood:'JP Nagar',coords:[12.907,77.601],address:'Bannerghatta Road, JP Nagar, Bengaluru',tag:'South Bengaluru',description:'A south Bengaluru mall with a large food-service directory.',source:'https://www.scai.in/portfolio/nexus-vega-city-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'hatti-kaapi-vega',title:'Hatti Kaapi · Nexus Vega City',category:'cafes',neighbourhood:'JP Nagar',coords:[12.9072,77.6012],address:'Inside Nexus Vega City, Bannerghatta Road',tag:'Local coffee',description:'Listed in the centre directory. Check the mall for current hours and availability.',source:'https://www.scai.in/portfolio/nexus-vega-city-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'kailash-vega',title:'Kailash Parbat · Nexus Vega City',category:'food',neighbourhood:'JP Nagar',coords:[12.9068,77.6008],address:'Inside Nexus Vega City, Bannerghatta Road',tag:'Inside a mall',description:'An Indian food option listed in the mall directory. Confirm hours with the centre.',source:'https://www.scai.in/portfolio/nexus-vega-city-bangalore/',sourceLabel:'SCAI mall directory'},
 {id:'kailash-orion',title:'Kailash Parbat · Orion Mall',category:'food',neighbourhood:'Rajajinagar',coords:[13.0125,77.5551],address:'Inside Orion Mall, Brigade Gateway, Rajajinagar',tag:'Inside a mall',description:'Orion Mall has a dedicated page for this restaurant. Check it for the latest dining details.',source:'https://www.orionmalls.com/orion-mall-at-brigade-gateway/dine/kailash-parbat',sourceLabel:'Orion Mall restaurant page'},
 {id:'dessert-works-orion',title:'Dessert Works · Orion Mall',category:'cafes',neighbourhood:'Rajajinagar',coords:[13.0121,77.5547],address:'Inside Orion Mall, Brigade Gateway, Rajajinagar',tag:'Sweet stop',description:'A dessert stop on Orion Mall’s dining directory. Verify current opening details on the mall page.',source:'https://www.orionmalls.com/orion-mall-at-brigade-gateway/dine/dessert-works',sourceLabel:'Orion Mall restaurant page'}
];
